package pcode

import "fmt"

// OpCode mirrors the core p-code opcode identifiers from Ghidra.
type OpCode uint16

const (
	CPUI_COPY OpCode = 1 + iota
	CPUI_LOAD
	CPUI_STORE
	CPUI_BRANCH
	CPUI_CBRANCH
	CPUI_BRANCHIND
	CPUI_CALL
	CPUI_CALLIND
	CPUI_CALLOTHER
	CPUI_RETURN
	CPUI_INT_EQUAL
	CPUI_INT_NOTEQUAL
	CPUI_INT_SLESS
	CPUI_INT_SLESSEQUAL
	CPUI_INT_LESS
	CPUI_INT_LESSEQUAL
	CPUI_INT_ZEXT
	CPUI_INT_SEXT
	CPUI_INT_ADD
	CPUI_INT_SUB
	CPUI_INT_CARRY
	CPUI_INT_SCARRY
	CPUI_INT_SBORROW
	CPUI_INT_2COMP
	CPUI_INT_NEGATE
	CPUI_INT_XOR
	CPUI_INT_AND
	CPUI_INT_OR
	CPUI_INT_LEFT
	CPUI_INT_RIGHT
	CPUI_INT_SRIGHT
	CPUI_INT_MULT
	CPUI_INT_DIV
	CPUI_INT_SDIV
	CPUI_INT_REM
	CPUI_INT_SREM
	CPUI_BOOL_NEGATE
	CPUI_BOOL_XOR
	CPUI_BOOL_AND
	CPUI_BOOL_OR
	CPUI_FLOAT_EQUAL
	CPUI_FLOAT_NOTEQUAL
	CPUI_FLOAT_LESS
	CPUI_FLOAT_LESSEQUAL
	_
	CPUI_FLOAT_NAN
	CPUI_FLOAT_ADD
	CPUI_FLOAT_DIV
	CPUI_FLOAT_MULT
	CPUI_FLOAT_SUB
	CPUI_FLOAT_NEG
	CPUI_FLOAT_ABS
	CPUI_FLOAT_SQRT
	CPUI_FLOAT_INT2FLOAT
	CPUI_FLOAT_FLOAT2FLOAT
	CPUI_FLOAT_TRUNC
	CPUI_FLOAT_CEIL
	CPUI_FLOAT_FLOOR
	CPUI_FLOAT_ROUND
	CPUI_MULTIEQUAL
	CPUI_INDIRECT
	CPUI_PIECE
	CPUI_SUBPIECE
	CPUI_CAST
	CPUI_PTRADD
	CPUI_PTRSUB
	CPUI_SEGMENTOP
	CPUI_CPOOLREF
	CPUI_NEW
	CPUI_INSERT
	CPUI_ZPULL
	CPUI_POPCOUNT
	CPUI_LZCOUNT
	CPUI_SPULL
	CPUI_MAX
)

var opcodeNames = map[OpCode]string{
	CPUI_COPY:              "COPY",
	CPUI_LOAD:              "LOAD",
	CPUI_STORE:             "STORE",
	CPUI_BRANCH:            "BRANCH",
	CPUI_CBRANCH:           "CBRANCH",
	CPUI_BRANCHIND:         "BRANCHIND",
	CPUI_CALL:              "CALL",
	CPUI_CALLIND:           "CALLIND",
	CPUI_CALLOTHER:         "CALLOTHER",
	CPUI_RETURN:            "RETURN",
	CPUI_INT_EQUAL:         "INT_EQUAL",
	CPUI_INT_NOTEQUAL:      "INT_NOTEQUAL",
	CPUI_INT_SLESS:         "INT_SLESS",
	CPUI_INT_SLESSEQUAL:    "INT_SLESSEQUAL",
	CPUI_INT_LESS:          "INT_LESS",
	CPUI_INT_LESSEQUAL:     "INT_LESSEQUAL",
	CPUI_INT_ZEXT:          "INT_ZEXT",
	CPUI_INT_SEXT:          "INT_SEXT",
	CPUI_INT_ADD:           "INT_ADD",
	CPUI_INT_SUB:           "INT_SUB",
	CPUI_INT_CARRY:         "INT_CARRY",
	CPUI_INT_SCARRY:        "INT_SCARRY",
	CPUI_INT_SBORROW:       "INT_SBORROW",
	CPUI_INT_2COMP:         "INT_2COMP",
	CPUI_INT_NEGATE:        "INT_NEGATE",
	CPUI_INT_XOR:           "INT_XOR",
	CPUI_INT_AND:           "INT_AND",
	CPUI_INT_OR:            "INT_OR",
	CPUI_INT_LEFT:          "INT_LEFT",
	CPUI_INT_RIGHT:         "INT_RIGHT",
	CPUI_INT_SRIGHT:        "INT_SRIGHT",
	CPUI_INT_MULT:          "INT_MULT",
	CPUI_INT_DIV:           "INT_DIV",
	CPUI_INT_SDIV:          "INT_SDIV",
	CPUI_INT_REM:           "INT_REM",
	CPUI_INT_SREM:          "INT_SREM",
	CPUI_BOOL_NEGATE:       "BOOL_NEGATE",
	CPUI_BOOL_XOR:          "BOOL_XOR",
	CPUI_BOOL_AND:          "BOOL_AND",
	CPUI_BOOL_OR:           "BOOL_OR",
	CPUI_FLOAT_EQUAL:       "FLOAT_EQUAL",
	CPUI_FLOAT_NOTEQUAL:    "FLOAT_NOTEQUAL",
	CPUI_FLOAT_LESS:        "FLOAT_LESS",
	CPUI_FLOAT_LESSEQUAL:   "FLOAT_LESSEQUAL",
	CPUI_FLOAT_NAN:         "FLOAT_NAN",
	CPUI_FLOAT_ADD:         "FLOAT_ADD",
	CPUI_FLOAT_DIV:         "FLOAT_DIV",
	CPUI_FLOAT_MULT:        "FLOAT_MULT",
	CPUI_FLOAT_SUB:         "FLOAT_SUB",
	CPUI_FLOAT_NEG:         "FLOAT_NEG",
	CPUI_FLOAT_ABS:         "FLOAT_ABS",
	CPUI_FLOAT_SQRT:        "FLOAT_SQRT",
	CPUI_FLOAT_INT2FLOAT:   "FLOAT_INT2FLOAT",
	CPUI_FLOAT_FLOAT2FLOAT: "FLOAT_FLOAT2FLOAT",
	CPUI_FLOAT_TRUNC:       "FLOAT_TRUNC",
	CPUI_FLOAT_CEIL:        "FLOAT_CEIL",
	CPUI_FLOAT_FLOOR:       "FLOAT_FLOOR",
	CPUI_FLOAT_ROUND:       "FLOAT_ROUND",
	CPUI_MULTIEQUAL:        "MULTIEQUAL",
	CPUI_INDIRECT:          "INDIRECT",
	CPUI_PIECE:             "PIECE",
	CPUI_SUBPIECE:          "SUBPIECE",
	CPUI_CAST:              "CAST",
	CPUI_PTRADD:            "PTRADD",
	CPUI_PTRSUB:            "PTRSUB",
	CPUI_SEGMENTOP:         "SEGMENTOP",
	CPUI_CPOOLREF:          "CPOOLREF",
	CPUI_NEW:               "NEW",
	CPUI_INSERT:            "INSERT",
	CPUI_ZPULL:             "ZPULL",
	CPUI_POPCOUNT:          "POPCOUNT",
	CPUI_LZCOUNT:           "LZCOUNT",
	CPUI_SPULL:             "SPULL",
	CPUI_MAX:               "MAX",
}

func (o OpCode) String() string {
	if name, ok := opcodeNames[o]; ok {
		return name
	}
	return fmt.Sprintf("OpCode(%d)", uint16(o))
}
